Add check for non-empty image references

diff --git a/.github/workflows/self-tests.yml b/.github/workflows/self-tests.yml
--- a/.github/workflows/self-tests.yml
+++ b/.github/workflows/self-tests.yml
@@ -169,3 +169,9 @@ jobs:
         run: |
           echo "Expected attempting to cache nothing to fail"
           exit 1
+
+      - name: Fail if no failure detected
+        if: ${{ !failure() }}
+        run: |
+          echo "Expected attempting to cache nothing to fail"
+          exit 1
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -42,6 +42,15 @@ runs:
         echo "::error title=${{ github.job }} - Can't Cache Latest::One/more images is a reference to a ':latest' tag which cannot be cached"
         exit 1
 
+    - name: Check at least one image reference was provided
+      shell: bash
+      run: |
+        IMAGES=$(echo -n "${{ inputs.images }}" | tr -d ' ')
+        if [ -z "${IMAGES}" ]; then
+          echo "::error title=${{ github.job }} - No Images to Cache::One/more image references MUST be supplied"
+          exit 1
+        fi
+
     - name: Generate Cache Key
       id: cache-key
       shell: bash
